-- MySQL Script generated by MySQL Workbench
-- Mon May 20 00:59:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema massaia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema massaia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `massaia` DEFAULT CHARACTER SET utf8 ;
USE `massaia` ;

-- -----------------------------------------------------
-- Table `massaia`.`albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massaia`.`albums` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `cover` VARCHAR(255) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `massaia`.`songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massaia`.`songs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `album_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `position` TINYINT NOT NULL,
  `lyrics` TEXT NULL,
  `audio` VARCHAR(255) NULL,
  `video` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_music_album_idx` (`album_id` ASC) VISIBLE,
  CONSTRAINT `fk_music_album`
    FOREIGN KEY (`album_id`)
    REFERENCES `massaia`.`albums` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `massaia`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massaia`.`authors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NULL,
  `title` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `massaia`.`art_pieces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massaia`.`art_pieces` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `song_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_at_piece_music1_idx` (`song_id` ASC) VISIBLE,
  INDEX `fk_at_piece_author1_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_at_piece_music1`
    FOREIGN KEY (`song_id`)
    REFERENCES `massaia`.`songs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_at_piece_author1`
    FOREIGN KEY (`author_id`)
    REFERENCES `massaia`.`authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `massaia`.`moments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massaia`.`moments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `video` VARCHAR(255) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `massaia`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massaia`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `massaia`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massaia`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `massaia`.`songs_has_authors_has_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `massaia`.`songs_has_authors_has_roles` (
  `roles_id` INT NOT NULL,
  `songs_id` INT NOT NULL,
  `authors_id` INT NOT NULL,
  PRIMARY KEY (`roles_id`, `songs_id`, `authors_id`),
  INDEX `fk_songs_has_authors_has_roles_roles1_idx` (`roles_id` ASC) VISIBLE,
  INDEX `fk_songs_has_authors_has_roles_songs1_idx` (`songs_id` ASC) VISIBLE,
  INDEX `fk_songs_has_authors_has_roles_authors1_idx` (`authors_id` ASC) VISIBLE,
  CONSTRAINT `fk_songs_has_authors_has_roles_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `massaia`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songs_has_authors_has_roles_songs1`
    FOREIGN KEY (`songs_id`)
    REFERENCES `massaia`.`songs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songs_has_authors_has_roles_authors1`
    FOREIGN KEY (`authors_id`)
    REFERENCES `massaia`.`authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
